export const languageData = {
  count: 21,
  next: null,
  previous: null,
  results: [
    { id: 1, language: "Python", slug: "python" },
    { id: 2, language: "JavaScript", slug: "javascript" },
    { id: 3, language: "Java", slug: "java" },
    { id: 4, language: "C#", slug: "csharp" },
    { id: 5, language: "C++", slug: "cpp" },
    { id: 6, language: "Ruby", slug: "ruby" },
    { id: 7, language: "Swift", slug: "swift" },
    { id: 8, language: "Kotlin", slug: "kotlin" },
    { id: 9, language: "PHP", slug: "php" },
    { id: 10, language: "TypeScript", slug: "typescript" },
    { id: 11, language: "Go", slug: "go" },
    { id: 12, language: "Rust", slug: "rust" },
    { id: 13, language: "HTML", slug: "html" },
    { id: 14, language: "CSS", slug: "css" },
    { id: 15, language: "SQL", slug: "sql" },
    { id: 16, language: "MATLAB", slug: "matlab" },
    { id: 17, language: "R", slug: "r" },
    {
      id: 18,
      language: "Shell Scripting Languages",
      slug: "shell",
    },
    { id: 19, language: "Perl", slug: "perl" },
    { id: 20, language: "Scala", slug: "scala" },
    { id: 21, language: "Dart", slug: "dart" },
  ],
};

export const languageMap: { [k: string]: string } = {
  python: "Python",
  javascript: "JavaScript",
  java: "Java",
  csharp: "C#",
  cpp: "C++",
  ruby: "Ruby",
  swift: "Swift",
  kotlin: "Kotlin",
  php: "PHP",
  typescript: "TypeScript",
  go: "Go",
  rust: "Rust",
  html: "HTML",
  css: "CSS",
  sql: "SQL",
  matlab: "MATLAB",
  r: "R",
  shell: "Shell Scripting",
  perl: "Perl",
  scala: "Scala",
  dart: "Dart",
};
