# Generated by Django 4.2.10 on 2024-04-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_language_slug_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
