# Generated by Django 4.2.10 on 2024-04-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_snippet_user_alter_snippet_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='user',
        ),
    ]
