# Generated by Django 4.2.10 on 2024-04-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_snippet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
