# Generated by Django 4.2.10 on 2024-04-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
