# Generated by Django 4.2.10 on 2024-04-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='editedAt',
            new_name='edited_at',
        ),
    ]
