# Generated by Django 4.2.10 on 2024-04-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_createdat_snippet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_language', to='backend.language'),
        ),
    ]
